"""Unit test for the session audit proxy route."""

from __future__ import annotations

import os
from unittest.mock import AsyncMock, MagicMock

import pytest_asyncio
from httpx import ASGITransport, AsyncClient

from .office_db import FakeDB

os.environ.setdefault("JWT_SECRET_KEY", "test-secret-key-32-bytes-1234567")
os.environ.setdefault("JWT_ALGORITHM", "HS256")
os.environ.setdefault("DATABASE_URL", "postgresql://test:test@localhost:5432/test")
os.environ.setdefault("REDIS_URL", "redis://localhost:6379/1")
os.environ.setdefault("SUPERAGENT_URL", "http://127.0.0.1:8001")
os.environ.setdefault("REGISTRY_URL", "http://127.0.0.1:8003")

_AUDIT_PAYLOAD = {
    "session_id": "sess-123",
    "generated_at": "2026-07-26T12:00:00+00:00",
    "goal": "Show me my portfolio",
    "summary": {
        "total_steps": 1,
        "steps_verified": 1,
        "steps_failed": 0,
        "protocols": ["A2A"],
        "total_cost_usd": "0.01",
        "duration_ms": 1200,
    },
    "steps": [
        {
            "seq": 1,
            "agent_id": "did:orcha:agent:finance-dashboard",
            "capability_id": "get_portfolio",
            "protocol": "A2A",
            "internal_tool_name": "finance_dashboard__get_portfolio",
            "verified": True,
            "verdict_reason": "ok",
            "total_cost_usd": "0.01",
        }
    ],
    "note": "Generated by Orcha Verified Runs — per-step evidence.",
}


@pytest_asyncio.fixture
async def client_with_mocks():
    from gateway.auth.jwt import create_access_token
    from gateway.main import app

    redis = AsyncMock()
    redis.sismember = AsyncMock(return_value=False)
    # the session's owner, and (story 2.0) its office: the caller's personal one
    redis.get = AsyncMock(
        side_effect=lambda key: (
            "po_user-001" if key.startswith("gateway:session-office:") else "user-001"
        )
    )

    app.state.redis = redis
    app.state.db = FakeDB()
    app.state.superagent = AsyncMock()

    token, _ = create_access_token(user_id="user-001", email="test@example.com")
    headers = {"Authorization": f"Bearer {token}"}

    async with AsyncClient(
        transport=ASGITransport(app=app), base_url="http://test"
    ) as ac:
        yield ac, app.state.superagent, headers


def _sa_response(status_code: int, payload: dict) -> MagicMock:
    resp = MagicMock()
    resp.status_code = status_code
    resp.json = MagicMock(return_value=payload)
    resp.raise_for_status = MagicMock()
    return resp


async def test_audit_proxy_success(client_with_mocks):
    ac, sa, headers = client_with_mocks
    sa.get = AsyncMock(return_value=_sa_response(200, _AUDIT_PAYLOAD))

    resp = await ac.get("/api/v1/sessions/sess-123/audit", headers=headers)

    assert resp.status_code == 200
    assert resp.json() == _AUDIT_PAYLOAD
    sa.get.assert_awaited_once_with(
        "/sessions/sess-123/audit", params={"user_id": "user-001"}
    )


async def test_audit_proxy_superagent_404_maps_to_404(client_with_mocks):
    ac, sa, headers = client_with_mocks
    sa.get = AsyncMock(return_value=_sa_response(404, {"detail": "Session not found"}))

    resp = await ac.get("/api/v1/sessions/sess-123/audit", headers=headers)

    assert resp.status_code == 404


async def test_audit_proxy_requires_auth(client_with_mocks):
    ac, _, _ = client_with_mocks
    resp = await ac.get("/api/v1/sessions/sess-123/audit")
    assert resp.status_code in (401, 403)
