#!/usr/bin/env python3
"""Generate the RFC 0003 golden vectors from the RFC's own worked example.

Every value in ``run-attestation-golden.json`` — both ``args_hash`` /
``output_hash`` pairs, both step-commitment roots, the signed digest and the
signature — is derived here from the example inputs and the example-only
Ed25519 seed ``00 01 02 … 1f``. Nothing is transcribed by hand, so the
vectors are reproducible by anyone and a drift between the RFC text, the
vectors and the verifier fails a test instead of sitting green.

The generator depends only on the SDK's vendored verifier
(``emerge.run_attestation``) and ``cryptography`` — the same footprint an
offline verifier has — so it runs with no platform service and ships with
the spec.

Usage (from the repository root)::

    uv run python docs/spec/test-vectors/generate_run_attestation_golden.py
        rewrite run-attestation-golden.json in place

    uv run python docs/spec/test-vectors/generate_run_attestation_golden.py --check
        exit 1 if the committed file differs from a fresh generation

    uv run python docs/spec/test-vectors/generate_run_attestation_golden.py --print-example
        print the ``valid`` envelope as the JSON block the RFC's
        "Worked example" section carries (paste it there verbatim)

Self-checks run on every invocation: the seed must produce the public key
the RFC prints, the ``valid`` envelope must pass all four verifier checks,
and the ``tampered`` envelope must fail the chain root, the Merkle root AND
the signature — each asserted independently, because the verifier stops at
the first failure and a tamper that broke only one commitment would be a
regression in the vector, not a pass.
"""

from __future__ import annotations

import argparse
import base64
import copy
import json
import sys
from pathlib import Path
from typing import Any

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from emerge.run_attestation import (
    RUN_ATTESTATION_FORMAT,
    canonical_json_bytes,
    compute_envelope_digest,
    compute_steps_merkle_root,
    compute_steps_root,
    sha256_hex,
    verify_run_attestation,
)

VECTORS_PATH = Path(__file__).resolve().with_name("run-attestation-golden.json")

# The example-only signing seed the RFC names: bytes 0x00 … 0x1f.
EXAMPLE_SEED = bytes(range(32))
EXAMPLE_SEED_B64 = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="
EXAMPLE_PUBLIC_KEY_B64 = "A6EHv/POEL4dcN0Y50vAmWfk1jCbpQ1fHdyGZBJVMbg="

# The worked example's raw inputs (RFC 0003, "Worked example"). Raw args and
# outputs never enter the envelope — only their hashes do.
EXAMPLE_RAW_STEPS: list[dict[str, Any]] = [
    {
        "call_id": "call-7f3a",
        "tool": "search_docs",
        "args": {"query": "refund policy"},
        "output": {"documents": ["policy-v3"], "count": 1},
        "success": True,
        "latency_ms": 132,
    },
    {
        "call_id": "call-7f3b",
        "tool": "summarize",
        "args": {"text": "policy-v3 contents", "max_words": 50},
        "output": {"summary": "Refunds within 30 days."},
        "success": True,
        "latency_ms": 481,
        "cdv_bp": 910,
    },
]

DESCRIPTION = (
    "RFC 0003 (orcha.run-attestation/v1) golden vectors, shared across sdk, "
    "node, validator and playground test suites. Generated by "
    "generate_run_attestation_golden.py from the RFC worked example and the "
    "example-only seed 00 01 02 ... 1f — never edited by hand. 'valid' is the "
    "RFC worked example byte-for-byte (all hashes, both step-commitment roots, "
    "the digest, and the signature are real values computed per the RFC). "
    "'tampered' is the same envelope with steps[0].latency_ms changed "
    "132 -> 133: still schema-valid, but BOTH step-commitment recomputations "
    "(steps_root and steps_merkle_root) and signature verification MUST fail."
)


def _hashed_step(seq: int, raw: dict[str, Any]) -> dict[str, Any]:
    step: dict[str, Any] = {
        "seq": seq,
        "call_id": raw["call_id"],
        "tool": raw["tool"],
        "args_hash": sha256_hex(canonical_json_bytes(raw["args"])),
        "output_hash": sha256_hex(canonical_json_bytes(raw["output"])),
        "success": raw["success"],
        "latency_ms": raw["latency_ms"],
    }
    if "cdv_bp" in raw:
        step["cdv_bp"] = raw["cdv_bp"]
    return step


def build_valid_envelope() -> dict[str, Any]:
    """The RFC worked example, built and signed per the RFC's rules."""
    private_key = Ed25519PrivateKey.from_private_bytes(EXAMPLE_SEED)
    public_key_b64 = base64.b64encode(
        private_key.public_key().public_bytes_raw()
    ).decode("ascii")
    if public_key_b64 != EXAMPLE_PUBLIC_KEY_B64:
        raise AssertionError(
            "the example seed no longer yields the public key the RFC prints"
        )

    steps = [_hashed_step(seq, raw) for seq, raw in enumerate(EXAMPLE_RAW_STEPS)]
    unsigned: dict[str, Any] = {
        "format": RUN_ATTESTATION_FORMAT,
        "run_id": "run-9c2e-example",
        "agent_dids": ["did:orcha:agent:example-support-bot"],
        "charter_hash": None,
        "policy_version": "example-policy/1.0",
        "steps": steps,
        "steps_root": compute_steps_root(steps),
        "steps_merkle_root": compute_steps_merkle_root(steps),
        "verdicts": [{"check": "authorized_scope", "result": "pass"}],
        "started_at": "2026-08-06T00:58:21Z",
        "finished_at": "2026-08-06T00:58:24Z",
        "signer": {
            "did": "did:orcha:system:validator",
            "public_key_b64": public_key_b64,
        },
    }
    digest = compute_envelope_digest(unsigned)
    signature = base64.b64encode(private_key.sign(digest.encode("utf-8"))).decode(
        "ascii"
    )
    return {**unsigned, "signature": signature}


def build_tampered_envelope(valid: dict[str, Any]) -> dict[str, Any]:
    """One byte of one step changed; every commitment must notice."""
    tampered = copy.deepcopy(valid)
    tampered["steps"][0]["latency_ms"] = 133
    return tampered


def self_check(valid: dict[str, Any], tampered: dict[str, Any]) -> None:
    verdict = verify_run_attestation(valid)
    if not verdict.valid:
        raise AssertionError(f"valid vector does not verify: {verdict.checks}")

    # Independent assertions, not the verifier's short-circuit: each
    # commitment must fail on its own.
    if compute_steps_root(tampered["steps"]) == tampered["steps_root"]:
        raise AssertionError("tamper did not break steps_root")
    if compute_steps_merkle_root(tampered["steps"]) == tampered["steps_merkle_root"]:
        raise AssertionError("tamper did not break steps_merkle_root")
    if compute_envelope_digest(tampered) == compute_envelope_digest(valid):
        raise AssertionError("tamper did not change the signed digest")
    tampered_verdict = verify_run_attestation(tampered)
    if tampered_verdict.valid or not tampered_verdict.checks["schema"]:
        raise AssertionError(
            "tampered vector must stay schema-valid and fail verification"
        )


def build_vectors() -> dict[str, Any]:
    valid = build_valid_envelope()
    tampered = build_tampered_envelope(valid)
    self_check(valid, tampered)
    return {
        "description": DESCRIPTION,
        "source": (
            "docs/spec/rfcs/0003-run-attestation-envelope.md (worked example); "
            "generator: docs/spec/test-vectors/generate_run_attestation_golden.py"
        ),
        "valid": valid,
        "tampered": tampered,
    }


def render(value: Any) -> str:
    return json.dumps(value, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed vectors differ from a fresh generation",
    )
    mode.add_argument(
        "--print-example",
        action="store_true",
        help="print the RFC worked-example JSON block (the 'valid' envelope)",
    )
    args = parser.parse_args(argv)

    vectors = build_vectors()
    if args.print_example:
        sys.stdout.write(render(vectors["valid"]))
        return 0
    rendered = render(vectors)
    if args.check:
        committed = VECTORS_PATH.read_text(encoding="utf-8")
        if committed != rendered:
            sys.stderr.write(
                f"{VECTORS_PATH} differs from a fresh generation — regenerate it\n"
            )
            return 1
        print(f"{VECTORS_PATH.name}: reproducible")
        return 0
    VECTORS_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {VECTORS_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
