"""Run evidence — assemble a session's audit (evidence package) from transcript rows."""

from __future__ import annotations

import contextlib
import logging
from dataclasses import dataclass
from datetime import UTC, datetime
from decimal import Decimal, InvalidOperation
from typing import Any

from common.utils.src import firing_view

from ..persistence.transcript_store import TRANSCRIPT_TOOL_META_KEY
from .models import (
    RunAuditCoverage,
    RunAuditFiring,
    RunAuditGate,
    RunAuditResponse,
    RunAuditSettlement,
    RunAuditStep,
    RunAuditSummary,
)

logger = logging.getLogger(__name__)

_AUDIT_NOTE = (
    "Generated by Metaorcha: the session's transcript of tool calls, and the "
    "settlement gate's decision for the run where one is recorded. The "
    "coverage block says what the signed receipt does and does not cover."
)
# emerge.run_attestation.COVERAGE_STATEMENT, used only where the SDK is not
# installed so the export still states its coverage (FR-8); a test pins the
# two equal, and _coverage_without_sdk to coverage_statement, so there is one
# text and one reading.
_COVERAGE_FALLBACK = (
    "Of the work done, this receipt commits to the tool calls listed in its "
    "steps, in order, and to the verdicts signed beside them (such as which "
    "model ran); it commits to nothing else. Model (LLM) calls are not steps, "
    "and neither is any work the producer did not record as a tool call, such "
    "as planning. A call refused before it ran may appear as a failed step or "
    "not at all. That something is absent from the steps does not show that "
    "it did not happen."
)
_EXPORT_STEPS_UNSIGNED = (
    "This export's step list is the session's transcript of tool calls across "
    "all of its runs, including calls refused before they ran; it is not itself "
    "signed."
)
_NO_RECEIPT_READ = "No signed receipt was read for this export."
_RECEIPT_UNVERIFIED = (
    "A stored receipt for run {run_id} did not verify when this export was "
    "built; nothing is read from it."
)
_RECEIPT_UNCHECKED = (
    "The stored receipt for run {run_id} has {steps} step(s); this export could "
    "not check its signature (the verifier is not installed)."
)
_GOAL_MAX_LEN = 500


def _row_role(row: Any) -> str:
    r = getattr(row, "role", "")
    s = getattr(r, "name", None) or str(r)
    return s.rsplit(".", 1)[-1]


def _step_cost(meta: dict[str, Any]) -> Decimal:
    raw = meta.get("total_cost_usd")
    if not isinstance(raw, str) or not raw:
        return Decimal(0)
    try:
        return Decimal(raw)
    except InvalidOperation:
        return Decimal(0)


@dataclass(frozen=True)
class SettlementEvidence:
    """What the export says about the session's sealed run and its settlement."""

    run_id: str | None = None
    gate: RunAuditGate | None = None
    settlement: RunAuditSettlement | None = None
    firing: RunAuditFiring | None = None
    envelope: dict[str, Any] | None = None  # the run's stored envelope, as read


def _coverage_without_sdk(envelope: Any) -> dict[str, Any]:
    """``coverage_statement`` where the SDK is absent; a test pins the two equal."""
    steps = envelope.get("steps") if isinstance(envelope, dict) else None
    tools: list[str] = []
    for step in steps if isinstance(steps, list) else []:
        tool = step.get("tool") if isinstance(step, dict) else None
        if isinstance(tool, str) and tool not in tools:
            tools.append(tool)
    return {
        "statement": _COVERAGE_FALLBACK,
        "steps": len(steps) if isinstance(steps, list) else None,
        "tools": tools,
    }


def receipt_verifies(envelope: Any) -> bool | None:
    """Whether the stored envelope verifies offline: True, False, or None
    when the verifier (SDK) is not installed. Never raises."""
    if not isinstance(envelope, dict):
        return False
    try:
        from emerge.run_attestation import verify_run_attestation
    except ImportError:
        return None
    try:
        return bool(verify_run_attestation(envelope).valid)
    except Exception:
        return False


def coverage(
    run_id: str | None, envelope: Any, verified: bool | None = None
) -> RunAuditCoverage:
    """What the export covers (FR-8): the verifier's statement, read from the envelope.

    The statement comes from the SDK (``coverage_statement``), the one place
    it is written; the export only adds how its own step list relates to the
    signed receipt. *verified* is :func:`receipt_verifies` for the envelope:
    a stored envelope that does not verify is not a signed receipt, and
    nothing is read from it. Never raises.
    """
    try:
        from emerge.run_attestation import coverage_statement
    except ImportError:
        coverage_statement = None
    read = (coverage_statement or _coverage_without_sdk)(envelope)
    unread = RunAuditCoverage(
        statement=read["statement"],
        export=f"{_NO_RECEIPT_READ} {_EXPORT_STEPS_UNSIGNED}",
    )
    if not (run_id and isinstance(envelope, dict) and read["steps"] is not None):
        return unread
    if verified is False:
        return RunAuditCoverage(
            statement=read["statement"],
            run_id=run_id,
            export=f"{_RECEIPT_UNVERIFIED.format(run_id=run_id)} {_EXPORT_STEPS_UNSIGNED}",
        )
    if verified is None:
        lead = _RECEIPT_UNCHECKED.format(run_id=run_id, steps=read["steps"])
    else:
        lead = f"The signed receipt for run {run_id} has {read['steps']} step(s)."
    return RunAuditCoverage(
        statement=read["statement"],
        run_id=run_id,
        receipt_steps=read["steps"],
        receipt_tools=list(read["tools"]),
        export=f"{lead} {_EXPORT_STEPS_UNSIGNED}",
    )


def run_models(envelope: Any, verified: bool | None = None) -> list[str] | None:
    """The receipt's signed ``model`` verdicts' details, or None with no receipt.

    None too for a stored envelope that does not verify: its verdicts are not
    signed by anyone the export can name (``receipt_verifies``). With the
    verifier not installed (None) they are read as stored.
    """
    if not isinstance(envelope, dict) or verified is False:
        return None
    verdicts = envelope.get("verdicts")
    if not isinstance(verdicts, list):
        return []
    out: list[str] = []
    for verdict in verdicts:
        if not isinstance(verdict, dict) or verdict.get("check") != "model":
            continue
        detail = verdict.get("detail")
        if isinstance(detail, str) and detail and detail not in out:
            out.append(detail)
    return out


def _gate(row: Any) -> RunAuditGate | None:
    if row is None:
        return None
    created = getattr(row, "created_at", None)
    return RunAuditGate(
        outcome=str(getattr(row, "outcome", "") or ""),
        failed_checks=firing_view.gate_checks(row),
        envelope_digest=str(getattr(row, "envelope_digest", "") or ""),
        created_at=created.isoformat() if isinstance(created, datetime) else "",
        charged=firing_view.gate_kind(row) == "charged",
    )


def _settlement(
    firing: Any, run_id: str, envelope: dict[str, Any], rows: list[Any]
) -> RunAuditSettlement | None:
    """The settlement block for a firing whose run sealed, keyed on the row's state.

    - ``attested_unsettled`` with no gate row: says no decision is recorded,
      and carries no field that implies one;
    - ``attested_unsettled`` with a gate row (not yet reconciled): None — the
      run-keyed ``gate`` block shows the row, and the export never
      contradicts itself;
    - ``settled`` / ``refused``: the gate's decision, verdict-only or charged;
    - any other state: None (the ``firing`` block carries it).
    """
    state = getattr(firing.state, "value", firing.state)
    if state == "attested_unsettled":
        if rows:
            return None
        return RunAuditSettlement(
            run_id=run_id,
            state=state,
            label=firing_view.state_label(state),
            gate_evaluated=False,
            statement=firing_view.STATEMENT_UNSETTLED,
        )
    if state not in ("settled", "refused"):
        return None
    row = firing_view.deciding_row(rows)
    kind = firing_view.gate_kind(row)
    untrusted = firing_view.envelope_untrusted(row)
    label = firing_view.state_label(state, firing.detail)
    if kind == "verdict_only":
        label = f"{label} — {firing_view.VERDICT_ONLY}"
        statement = firing_view.STATEMENT_VERDICT_ONLY
    elif kind == "charged":
        statement = firing_view.STATEMENT_CHARGED
    else:
        statement = firing_view.STATEMENT_ROW_UNREAD
    return RunAuditSettlement(
        run_id=run_id,
        state=state,
        label=label,
        gate_evaluated=True,
        verdict_only=None if kind is None else kind == "verdict_only",
        failed_checks=firing_view.gate_checks(row) if row is not None else None,
        # An envelope the gate found failed verification is no evidence of
        # what failed in it.
        failed_verdicts=None if untrusted else firing_view.failing_verdicts(envelope),
        statement=statement,
    )


async def _checks(
    client: Any, firing: Any, envelope: Any, untrusted: bool
) -> tuple[str | None, str | None]:
    """The routine's declared checks against the envelope, as the pane reads them."""
    try:
        routine = await client.workflowtemplate.find_unique(
            where={"id": firing.routine_id}
        )
    except Exception:  # noqa: BLE001 — degrade, never block the audit
        # the id comes from a request-selected row: escape line breaks so it
        # cannot forge a log line
        logger.warning(
            "audit: routine criteria not read for %s",
            str(firing.routine_id).replace("\r", "\\r").replace("\n", "\\n"),
        )
        return None, None
    if routine is None:
        return None, None
    return firing_view.checks_view(
        getattr(routine, "criteria", None), envelope, untrusted
    )


async def load_settlement(session_id: str, db: Any = None) -> SettlementEvidence:
    """The session's latest sealed run, its gate row, and (firings only) its settlement.

    - The run is the newest sealed run envelope in the session (case
      attestations are not seals), or the firing's ``run_id`` when nothing
      is found there.
    - ``gate`` is that run's deciding ledger row — keyed by run, never by
      session.
    - ``settlement`` is said only for a firing's session whose last sealed
      run is the firing's own (story 2.6). A chat run — including chat that
      went on in a firing's session — can carry a charge billed without the
      gate, and the export's totals cover the whole session; what that
      amounts to is not said here.

    Never raises: any failure degrades to saying nothing.
    """
    owns_db = False
    client = db
    try:
        if client is None:
            from src.generated_client import Prisma

            client = Prisma()
            await client.connect()
            owns_db = True
        from validator.run_envelope import get_run_attestation_by_run_id

        from ..workflow.scheduler import sealed_run_id

        firing = await client.routinefiring.find_unique(
            where={"session_id": session_id}
        )
        latest = await sealed_run_id(client, session_id)
        firing_run = getattr(firing, "run_id", None)
        run_id = latest or firing_run
        # The session went on as chat after the firing's run: the firing's
        # settlement would sit beside totals it does not describe.
        continued = bool(firing_run and latest and latest != firing_run)
        firing_block = None
        if firing is not None:
            state = getattr(firing.state, "value", firing.state)
            firing_block = RunAuditFiring(
                routine_id=str(firing.routine_id),
                state=str(state),
                label=firing_view.state_label(state, firing.detail),
                detail=firing.detail,
            )
        if not run_id:
            return SettlementEvidence(firing=firing_block)
        rows = list(
            await client.attestedsettlement.find_many(
                where={"run_id": run_id}, order={"created_at": "asc"}
            )
        )
        gate = _gate(firing_view.deciding_row(rows))
        envelope = await get_run_attestation_by_run_id(run_id, db=client)
        settlement = None
        if firing is not None and envelope is not None and not continued:
            settlement = _settlement(firing, run_id, envelope, rows)
            if settlement is not None:
                untrusted = firing_view.envelope_untrusted(
                    firing_view.deciding_row(rows)
                )
                kind, label = await _checks(client, firing, envelope, untrusted)
                settlement = settlement.model_copy(
                    update={"checks": kind, "checks_label": label}
                )
        return SettlementEvidence(
            run_id=run_id,
            gate=gate,
            settlement=settlement,
            firing=firing_block,
            envelope=envelope if isinstance(envelope, dict) else None,
        )
    except Exception:  # noqa: BLE001 — degrade, never block the audit
        # the id arrives in the request path: escape line breaks so it cannot
        # forge a log line
        logger.warning(
            "audit: settlement lookup failed for %s",
            session_id.replace("\r", "\\r").replace("\n", "\\n"),
        )
        return SettlementEvidence()
    finally:
        if owns_db and client is not None:
            with contextlib.suppress(Exception):
                await client.disconnect()


def build_run_audit(
    session_id: str,
    rows: list[Any],
    *,
    gate: RunAuditGate | None = None,
    evidence: SettlementEvidence | None = None,
    generated_at: datetime | None = None,
) -> RunAuditResponse:
    """
    Assemble the session's evidence package from SessionTranscriptEntry rows.

    Rows are Prisma records (or test fakes) with ``role`` / ``content`` /
    ``tool_inputs`` / ``created_at`` attributes. Steps come from TOOL rows whose
    ``tool_inputs`` carries the ``TRANSCRIPT_TOOL_META_KEY`` meta dict;
    ``invocation_args`` is deliberately omitted (may contain secrets).

    A step with no structural verdict (blocked, unresolved, system, or
    persisted before verdicts existed) is unchecked: ``verified`` None,
    counted in ``steps_unchecked`` and never as verified.
    """
    verified = receipt_verifies(evidence.envelope) if evidence else False
    generated_at = generated_at or datetime.now(UTC)

    goal = ""
    timestamps: list[datetime] = []
    for row in rows:
        created_at = getattr(row, "created_at", None)
        if isinstance(created_at, datetime):
            timestamps.append(created_at)
        if not goal and _row_role(row) == "USER":
            goal = str(getattr(row, "content", "") or "")[:_GOAL_MAX_LEN]

    steps: list[RunAuditStep] = []
    protocols: set[str] = set()
    total_cost = Decimal(0)
    for row in rows:
        if _row_role(row) != "TOOL":
            continue
        meta = getattr(row, "tool_inputs", None)
        # Persisted rows store the meta dict itself in tool_inputs; hydrated
        # messages nest it under TRANSCRIPT_TOOL_META_KEY. Accept both.
        if isinstance(meta, dict) and "agent_id" not in meta:
            nested = meta.get(TRANSCRIPT_TOOL_META_KEY)
            meta = nested if isinstance(nested, dict) else None
        if not isinstance(meta, dict) or "agent_id" not in meta:
            continue
        verified = meta.get("verified")
        verified = verified if isinstance(verified, bool) else None
        verdict_reason = str(meta.get("verdict_reason") or "")
        protocol = str(meta.get("protocol") or "")
        if protocol:
            protocols.add(protocol)
        total_cost += _step_cost(meta)
        steps.append(
            RunAuditStep(
                seq=len(steps) + 1,
                agent_id=str(meta.get("agent_id") or ""),
                capability_id=str(meta.get("capability_id") or ""),
                protocol=protocol,
                internal_tool_name=str(meta.get("internal_tool_name") or ""),
                verified=verified,
                verdict_reason=verdict_reason,
                base_fee=meta.get("base_fee")
                if isinstance(meta.get("base_fee"), str)
                else None,
                total_cost_usd=meta.get("total_cost_usd")
                if isinstance(meta.get("total_cost_usd"), str)
                else None,
            )
        )

    duration_ms: int | None = None
    if len(timestamps) >= 2:
        duration_ms = int((max(timestamps) - min(timestamps)).total_seconds() * 1000)

    return RunAuditResponse(
        session_id=session_id,
        generated_at=generated_at.isoformat(),
        goal=goal,
        summary=RunAuditSummary(
            total_steps=len(steps),
            steps_verified=sum(1 for s in steps if s.verified is True),
            steps_failed=sum(1 for s in steps if s.verified is False),
            steps_unchecked=sum(1 for s in steps if s.verified is None),
            protocols=sorted(protocols),
            total_cost_usd=str(total_cost.normalize()),
            duration_ms=duration_ms,
        ),
        steps=steps,
        note=_AUDIT_NOTE,
        coverage=coverage(
            evidence.run_id if evidence else None,
            evidence.envelope if evidence else None,
            verified,
        ),
        models=run_models(evidence.envelope, verified) if evidence else None,
        run_id=evidence.run_id if evidence else None,
        gate=evidence.gate if evidence else gate,
        settlement=evidence.settlement if evidence else None,
        firing=evidence.firing if evidence else None,
    )
